---
title: "ps4_models"
author: "James Bao"
date: "10/27/2020"
output: pdf_document
---

```{r}
library(plyr)
library(dplyr)
library(haven)
library(tidyverse)
library(nnet)
library(Metrics)
library(brms)
library(tidybayes)
library(statebins)
```




```{r}
raw_data <- read_dta("inputs/data/ns20200625/ns20200625.dta")
# Add the labels
raw_data <- labelled::to_factor(raw_data)
```


```{r}
reduced_data <- 
  raw_data %>% 
  select(vote_2020,
         state,
         race_ethnicity,
         age,
         gender,
         education)


#filtering out for only Trump and Biden voters
reduced_data <- reduced_data[reduced_data$vote_2020 == "Donald Trump" |
                             reduced_data$vote_2020 == "Joe Biden",]

# breaking age into groups of 18-29, 30-44, 45-60 and 60+
reduced_data$age_group <- cut(reduced_data$age, 
                              breaks = c(18, 29, 44, 60, 200),
                              labels = c("18-29","30-44","45-60","60+" ), 
                              right=FALSE)

#combine education options, helps match with post stratification data
reduced_data$education <- as.character(reduced_data$education)
reduced_data$education[
    grepl("Completed some graduate, but no degree", reduced_data$education)|
      grepl("Masters degree", reduced_data$education)|
      grepl("Doctorate degree", reduced_data$education)
  ] <- ('Graduate Education')
reduced_data$education[
    grepl("Associate Degree", reduced_data$education)|
      grepl("college", tolower(reduced_data$education))
  ] <- ('Post Secondary Degree')
reduced_data$education[
    grepl("Grade", reduced_data$education)|
      grepl("high school", tolower(reduced_data$education))
  ] <- ('High School or less')
reduced_data$education <- as.factor(reduced_data$education)


#combine race options, helps match with post stratification data
reduced_data$race_ethnicity <- as.character(reduced_data$race_ethnicity)
reduced_data$race_ethnicity[
    reduced_data$race_ethnicity == 'Asian (Asian Indian)' |
    reduced_data$race_ethnicity == 'Asian (Korean)' |
    reduced_data$race_ethnicity == 'Asian (Filipino)' |
    reduced_data$race_ethnicity == 'Asian (Vietnamese)'|
    grepl("Pacific", reduced_data$race_ethnicity)
  ] <- ('Asian (Other)')
reduced_data$race_ethnicity <- as.factor(reduced_data$race_ethnicity)

reduced_data$vote_enum <- if_else(reduced_data$vote_2020 == "Donald Trump", 0, 1 )


#drop unused levels
reduced_data <- droplevels(reduced_data)


total_rows <- nrow(reduced_data)
table(reduced_data$vote_2020)
table(reduced_data$age_group)
levels(reduced_data$education)
levels(reduced_data$gender)
levels(reduced_data$race_ethnicity)
reduced_data <- reduced_data %>% select(vote_2020,vote_enum, age_group, education, gender, 
                                        race_ethnicity, state)
```
```{r}
set.seed(50)
shuffle_indices <- sample(total_rows)
data <- reduced_data[shuffle_indices,]
boundary <- as.integer(total_rows*0.95)

training <- data[0:boundary,]
```


```{r}

model <- brm(formula = vote_2020 ~ state + race_ethnicity + gender + age_group,
             data = training,
             family = bernoulli(),
             control = list(adapt_delta = .99, 
                            max_treedepth = 15),
             chains = 3,
             iter = 2000,
             cores = 2
)
```

```{r}
# saveRDS(model, file = "model/3chain_2k-iter_no-edu_final.rds")

model <- readRDS("model/3chain_2k-iter_no-edu_final.rds")
```

```{r}
summary(model)
```


```{r}
testing <- data[boundary:total_rows,]
# probability <- model %>% add_predicted_draws(newdata = testing)

# training <- data[0:boundary,]
# training$vote_num <- if_else(training$vote_2020 == "Donald Trump", 1, 0 )

probability <- predict(model, type = "response", newdata = testing)
probability <- if_else(probability[,1] >0.5,1,0)

testing$probs <- probability

testing <- testing %>% mutate(acc = probs==vote_enum)

table(testing$acc)


# nrow(testing)
# 
# nrow(probability)
# summary(model)
```


```{r}
post_strat <- read_dta("inputs/data/usa_00001.dta")
# Add the labels
post_strat <- labelled::to_factor(post_strat)
```


```{r}
cleaned_post <- 
  post_strat %>% 
  select(stateicp,
         race,
         age,
         sex,
         educ
  )

cleaned_post$age <- as.character(cleaned_post$age)

cleaned_post$age[grepl("less than", cleaned_post$age)] <- "0"
cleaned_post$age[grepl("( in 1980 and 1990)", cleaned_post$age)] <- "90"
cleaned_post$age[grepl("(100+ in 1960-1970)", cleaned_post$age)] <- "100"
cleaned_post$age[grepl("(115+ in the 1990 internal data)", cleaned_post$age)
                 ] <- "115"
cleaned_post$age[grepl("(112+ in the 1980 internal data)", cleaned_post$age)
                 ] <- "112"
cleaned_post$age <- as.factor(cleaned_post$age)



cleaned_post$age <- as.numeric(cleaned_post$age)

cleaned_post <- cleaned_post[cleaned_post$age >= 18,]


cleaned_post$age_group <- cut(cleaned_post$age, breaks = c(18, 29, 44, 60, 200),
                              labels = c("18-29","30-44","45-60","60+" ),
                              right=FALSE)

cleaned_post$education <- as.character(cleaned_post$educ)

cleaned_post$education[
    grepl("5", cleaned_post$education)&
       grepl("years of college", cleaned_post$education)
  ] <- 'Graduate Education'

cleaned_post$education[
    grepl("college", cleaned_post$education)
  ] <- 'Post Secondary Degree'

cleaned_post$education[
    grepl("no schooling", cleaned_post$education)|
      grepl("grade", cleaned_post$education)
  ] <- 'High School or less'


cleaned_post$education <- as.factor(cleaned_post$education)


cleaned_post$race_ethnicity <- as.character(cleaned_post$race)
cleaned_post$race_ethnicity <- plyr::mapvalues(
  cleaned_post$race,
  c("white", "black/african american/negro", "american indian or alaska native",
    "chinese", "japanese", "other asian or pacific islander", "other race, nec",
    "two major races", "three or more major races" ),
  c("White", "Black, or African American", "American Indian or Alaska Native",
    "Asian (Chinese)", "Asian (Japanese)",  "Asian (Other)", "Some other race",
    "Some other race", "Some other race"))
cleaned_post$race_ethnicity <- as.factor(cleaned_post$race_ethnicity)


cleaned_post$gender <- plyr::mapvalues(cleaned_post$sex,
                                       c("male","female"),
                                       c("Male", "Female"))


cleaned_post$state <- as.character(cleaned_post$stateicp)

cleaned_post$state <- plyr::mapvalues(
  cleaned_post$stateicp, c(tolower(state.name), "district of columbia"),
  c(state.abb, "DC"))

cleaned_post$state <- as.factor(cleaned_post$state)

cleaned_post = cleaned_post[complete.cases(cleaned_post), ]

cleaned_post <- droplevels(cleaned_post)



cleaned_post <- cleaned_post %>% select(race_ethnicity, gender, education,
                                        state, age_group)
# total_rows <- nrow(cleaned_post)
# table(cleaned_post$gender)
# table(cleaned_post$education)
# table(cleaned_post$race_ethnicity)
# table(cleaned_post$state)
# table(cleaned_post$age_group)

```


```{r}
set.seed(101)
pred_post <- cleaned_post

pred_post <- pred_post[sample(nrow(pred_post)),]
pred_post <- pred_post[0:50000,]

probability <- predict(model, type = "response", newdata = pred_post)[,1]


```

```{r}
table(if_else(probability<=0.5,"Joe Biden",
                                  "Donald Trump" ))

summary(model)
```


