---
title: "ps4_models"
author: "James Bao"
date: "10/27/2020"
output: pdf_document
---

```{r}
library(haven)
library(tidyverse)
library(nnet)
```



```{r}
raw_data <- read_dta("inputs/data/usa_00001.dta")
# Add the labels
raw_data <- labelled::to_factor(raw_data)
```

```{r}
# Just keep some variables that may be of interest (change 
# this depending on your interests)
names(raw_data)

reduced_data <- 
  raw_data %>% 
  select(
         stateicp,
         sex,
         race, 
         educd,
         inctot)
         
head(reduced_data)
reduced_data$race %>% table()
reduced_data$stateicp %>% table()
reduced_data$educd %>% table()
reduced_data$sex %>% table()
reduced_data$inctot %>% table()


strat <- reduced_data
```

```{r}
raw_data <- read_dta("inputs/data/ns20200625/ns20200625.dta")
# Add the labels
raw_data <- labelled::to_factor(raw_data)
```

```{r}
reduced_data <- 
  raw_data %>% 
  select(vote_intention,
         vote_2020,
         state,
         race_ethnicity,
         age,
         gender,
         household_income
  )
reduced_data <- reduced_data[complete.cases(reduced_data), ]

reduced_data$race_ethnicity <- as.character(reduced_data$race_ethnicity)
reduced_data$race_ethnicity[
    reduced_data$race_ethnicity == 'Asian (Asian Indian)' |
    reduced_data$race_ethnicity == 'Asian (Korean)' |
    reduced_data$race_ethnicity == 'Asian (Filipino)' |
    reduced_data$race_ethnicity == 'Asian (Vietnamese)'|
    grepl("Pacific", reduced_data$race_ethnicity)
  ] <- ('Asian (Other)')
reduced_data$race_ethnicity <- as.factor(reduced_data$race_ethnicity)

levels(reduced_data$race_ethnicity )

```

```{r}
table(reduced_data$state)
table(reduced_data$race_ethnicity)
table(reduced_data$age)
table(reduced_data$gender)
table(reduced_data$household_income)

table(reduced_data$vote_intention)
table(reduced_data$vote_2020)
```
```{r}
model <- nnet::multinom(vote_2020 ~ state + race_ethnicity + gender + 
                          household_income, data = reduced_data)
model2 <- nnet::multinom(vote_2020 ~ household_income, data = reduced_data)
```
```{r}
summary(model)
```


```{r}
pre
```

